<h2><u> Data Cleaning Master List</u></h2>
<h4> This Notebook provides a series of python scripts that can be run for cleaning data. 
    <p> The scripts consist of the following:</p></h4>
    <p> 1.) Remove all Null Data  </p>
    <p> 2.) Remove Duplicate Rows </p>
    <p> 3.) Make Rows Proper Case </p> 
    <p> 4.) Convert PDF to CSV </p>
    <p> 5.) Dropping Columns </p> 
    <p> 6.) Rename Columns </p>  
    <h4><u> Dependancies Used:</u> </h4>
        <p> 1.) Pandas </p>
        <p> 2.) Geopandas </p>
        <p> 3.) Numpy </p>
    <h4><u> Dataset Used for Examples:</u> <a href="https://www.denvergov.org/opendata/dataset/city-and-county-of-denver-crime"> <p> Denver Crime Data- Last 5 years</p></a></h4>

<h2><u> 1. Removing All Null Data</u></h2> 
<h4> Source:  <a href= "https://code.likeagirl.io/how-to-use-python-to-remove-or-modify-empty-values-in-a-csv-dataset-34426c816347"> How-To Use Python to Remove or Modify Empty Values in a CSV Dataset By Leah Cole</a> 
    <p>  TLDR: There are two options for removing null values from a data set.</p> 
    <p> 1.) Remove all null values and put them in a seperate data frame. </p> 
    <p> 2.) Replace empty values with a space. </p>

In [3]:
# Step 1: Import your dependancies 
import pandas as pd
import numpy as np

In [4]:
# Step 2: Bring your csv file info a Dataframe
crimes = pd.read_csv(r"./Denver_Crime.csv")
# Step 2a: Show the first 5 rows by using  the head command. 
crimes.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,theft-other,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
1,2.015664e+09,2.020000e+15,5441,0,traffic-accident,traffic-accident,11/13/2015 7:45,NaN,11/13/2015 8:38,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1.0,122.0,west-colfax,0,1
2,2.017601e+10,2.020000e+16,2399,1,theft-bicycle,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,theft-from-bldg,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,violation-of-restraining-order,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0

In [6]:
# Step 3: Check the shape of your data using .shape command This tells you how many columns and rows you have in your dataset.
crimes.shape

(538172, 19)

In [7]:
# Step 4: Check for null values in your data set using the .isnull() command.
crimes.isnull()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538167,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
538168,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
538169,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
538170,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
538171,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
# Step 5: Get a sum of how many null values exisit in your data set. Use .isnull().sum 
crimes.isnull().sum()

INCIDENT_ID                    0
OFFENSE_ID                     0
OFFENSE_CODE                   0
OFFENSE_CODE_EXTENSION         0
OFFENSE_TYPE_ID                0
OFFENSE_CATEGORY_ID            0
FIRST_OCCURRENCE_DATE          0
LAST_OCCURRENCE_DATE      359272
REPORTED_DATE                  0
INCIDENT_ADDRESS           49426
GEO_X                       4604
GEO_Y                       4604
GEO_LON                     4605
GEO_LAT                     4605
DISTRICT_ID                    1
PRECINCT_ID                    1
NEIGHBORHOOD_ID                1
IS_CRIME                       0
IS_TRAFFIC                     0
dtype: int64

In [13]:
# Step 6: Check how many null values are in a specific column
crimes["LAST_OCCURRENCE_DATE"].isnull().sum()

359272

In [17]:
#Step 7: We are going to start with Option 2. Replacing all null values with a space. 
modifiedcrimes=crimes.fillna("")
#Check to see if there are any null values left. 
modifiedcrimes.isnull().sum()

INCIDENT_ID               0
OFFENSE_ID                0
OFFENSE_CODE              0
OFFENSE_CODE_EXTENSION    0
OFFENSE_TYPE_ID           0
OFFENSE_CATEGORY_ID       0
FIRST_OCCURRENCE_DATE     0
LAST_OCCURRENCE_DATE      0
REPORTED_DATE             0
INCIDENT_ADDRESS          0
GEO_X                     0
GEO_Y                     0
GEO_LON                   0
GEO_LAT                   0
DISTRICT_ID               0
PRECINCT_ID               0
NEIGHBORHOOD_ID           0
IS_CRIME                  0
IS_TRAFFIC                0
dtype: int64

In [18]:
# Step 8: Save your modified dataset to a new CSV
modifiedcrimes.to_csv('modifiedcrimes.csv',index=False)

In [19]:
# Option 2: Deleting the null values completely 
# Reminder you have two dataframes. Your crimes DF and modified crimes DF.
#Step 1: Use .dropna()
modified_crimes = crimes.dropna()

In [21]:
# Step 2: confirm that your modified_crimes dataframe doesnt have any null values by using the .sum() 
modified_crimes.isnull().sum()

INCIDENT_ID               0
OFFENSE_ID                0
OFFENSE_CODE              0
OFFENSE_CODE_EXTENSION    0
OFFENSE_TYPE_ID           0
OFFENSE_CATEGORY_ID       0
FIRST_OCCURRENCE_DATE     0
LAST_OCCURRENCE_DATE      0
REPORTED_DATE             0
INCIDENT_ADDRESS          0
GEO_X                     0
GEO_Y                     0
GEO_LON                   0
GEO_LAT                   0
DISTRICT_ID               0
PRECINCT_ID               0
NEIGHBORHOOD_ID           0
IS_CRIME                  0
IS_TRAFFIC                0
dtype: int64

In [24]:
#Step 3: You can once again make a CSV with the null values deleted competely. 
modified_crimes.to_csv('modified_crimes.csv',index=False)

<h2><u> 2. Remove Duplicate Rows </u></h2> 
<h4> Source: <a href = "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html">Pandas Drop Duplicate Rows </a>

In [5]:
crimes.drop_duplicates()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,theft-other,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
1,2.015664e+09,2.020000e+15,5441,0,traffic-accident,traffic-accident,11/13/2015 7:45,NaN,11/13/2015 8:38,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1.0,122.0,west-colfax,0,1
2,2.017601e+10,2.020000e+16,2399,1,theft-bicycle,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,theft-from-bldg,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,violation-of-restraining-order,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538167,2.020586e+09,2.020000e+15,1313,0,assault-simple,other-crimes-against-persons,9/30/2020 10:00,NaN,9/30/2020 11:26,8801 E MLK BLVD,3172894.0,1702787.0,-104.885013,39.761350,5.0,512.0,central-park,1,0
538168,2.020550e+09,2.020000e+15,1315,1,aggravated-assault-dv,aggravated-assault,9/12/2020 7:34,NaN,9/12/2020 7:34,5375 W 10TH AVE,3125094.0,1692507.0,-105.055214,39.733895,1.0,122.0,villa-park,1,0
538169,2.020601e+10,2.020000e+16,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,9/12/2020 14:45,9/12/2020 14:45,9/12/2020 14:57,902 27TH ST,3145983.0,1700959.0,-104.980771,39.756793,2.0,211.0,five-points,1,0
538170,2.020582e+09,2.020000e+15,5707,0,criminal-trespassing,all-other-crimes,9/28/2020 17:59,NaN,9/28/2020 17:59,1201 5TH ST,3137809.0,1695270.0,-105.009952,39.741300,1.0,123.0,auraria,1,0
538171,2.020601e+10,2.020000e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,9/26/2020 4:00,9/26/2020 5:00,9/26/2020 16:56,8200 BLK E 8TH AVE,3170620.0,1690662.0,-104.893389,39.728107,3.0,321.0,lowry-field,1,0

In [7]:
# Drop duplicates in a specfic column
crimes.drop_duplicates(subset=['LAST_OCCURRENCE_DATE'])

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,theft-other,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
2,2.017601e+10,2.020000e+16,2399,1,theft-bicycle,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,theft-from-bldg,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,violation-of-restraining-order,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0
5,2.018264e+09,2.020000e+15,1316,0,threats-to-injure,public-disorder,3/29/2018 10:00,4/17/2018 10:00,4/20/2018 13:33,1865 LARIMER ST,3142086.0,1699093.0,-104.994668,39.751731,6.0,612.0,union-station,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538147,2.020601e+10,2.020000e+16,2399,1,theft-bicycle,larceny,9/6/2020 14:55,9/9/2020 14:55,9/12/2020 15:00,140 S WASHINGTON ST,3146591.0,1685372.0,-104.978926,39.713994,3.0,311.0,speer,1,0
538148,2.020601e+10,2.020000e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,8/19/2020 23:59,8/20/2020 5:00,8/20/2020 19:55,394 N CLARKSON ST,3147015.0,1688370.0,-104.977358,39.722217,3.0,311.0,speer,1,0
538152,2.020482e+09,2.020000e+15,2203,0,burglary-business-by-force,burglary,8/8/2020 18:00,8/9/2020 21:54,8/9/2020 22:39,5100 W 44TH AVE,3125839.0,1707960.0,-105.052295,39.776306,1.0,111.0,berkeley,1,0
538164,2.020498e+09,2.020000e+15,2203,1,burg-auto-theft-busn-w-force,burglary,8/16/2020 23:58,8/17/2020 2:00,8/17/2020 6:37,465 N SANTA FE DR,3140926.0,1688815.0,-104.998995,39.723533,3.0,311.0,baker,1,0
538169,2.020601e+10,2.020000e+16,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,9/12/2020 14:45,9/12/2020 14:45,9/12/2020 14:57,902 27TH ST,3145983.0,1700959.0,-104.980771,39.756793,2.0,211.0,five-points,1,0

<h2><u> 3. Make Rows Proper Case </u></h2> 
<h4> Source: <a href="https://www.geeksforgeeks.org/python-pandas-series-str-lower-upper-and-title/"> GeeksforGeeks</a></h4>
<p> Note: The crimes dataframe is already properly cased. I'll run through each example of how to make the data upper, lower and proper or title case.  </p>

In [11]:
# Make a column all upper case
crimes["OFFENSE_TYPE_ID"]= crimes["OFFENSE_TYPE_ID"].str.upper()
crimes.head() # Notice that the text in the Offense_Type_id column is now all upper case.

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,THEFT-OTHER,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
1,2.015664e+09,2.020000e+15,5441,0,TRAFFIC-ACCIDENT,traffic-accident,11/13/2015 7:45,NaN,11/13/2015 8:38,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1.0,122.0,west-colfax,0,1
2,2.017601e+10,2.020000e+16,2399,1,THEFT-BICYCLE,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,THEFT-FROM-BLDG,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,VIOLATION-OF-RESTRAINING-ORDER,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0

In [13]:
# Make the OFFENSE_TYPE_ID column title case. 
crimes["OFFENSE_TYPE_ID"]= crimes["OFFENSE_TYPE_ID"].str.upper().str.title()
crimes.head() # In the forementioned column, the text is now proper case with the beginning of the word, being captialized.

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,Theft-Other,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
1,2.015664e+09,2.020000e+15,5441,0,Traffic-Accident,traffic-accident,11/13/2015 7:45,NaN,11/13/2015 8:38,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1.0,122.0,west-colfax,0,1
2,2.017601e+10,2.020000e+16,2399,1,Theft-Bicycle,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,Theft-From-Bldg,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,Violation-Of-Restraining-Order,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0

In [14]:
# Make column lowercase 
crimes["OFFENSE_TYPE_ID"]= crimes["OFFENSE_TYPE_ID"].str.lower()
crimes.head() #Now the data is returned to it's orginal state, which was all lowercase.

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2.018870e+09,2.020000e+15,2399,0,theft-other,larceny,12/27/2018 15:58,NaN,12/27/2018 16:51,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5.0,512.0,stapleton,1,0
1,2.015664e+09,2.020000e+15,5441,0,traffic-accident,traffic-accident,11/13/2015 7:45,NaN,11/13/2015 8:38,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1.0,122.0,west-colfax,0,1
2,2.017601e+10,2.020000e+16,2399,1,theft-bicycle,larceny,6/8/2017 13:15,6/8/2017 17:15,6/12/2017 8:44,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6.0,612.0,union-station,1,0
3,2.019601e+10,2.020000e+16,2308,0,theft-from-bldg,larceny,12/7/2019 13:07,12/7/2019 18:30,12/9/2019 13:35,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1.0,122.0,west-colfax,1,0
4,2.018862e+09,2.020000e+15,5016,0,violation-of-restraining-order,all-other-crimes,12/22/2018 20:15,12/22/2018 20:31,12/22/2018 22:00,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5.0,521.0,montbello,1,0

<h2> 4. Convert a PDF File to a CSV </h2> 
<h4> Notes: I created a specfic script for this task based on a 500 page pdf file. 
<p> You'll need to import another package using pip to get thsi script to work. 
    <p> Dependancy:<a href="https://pypi.org/project/tabula-py/">tabula-py</a> 
    <p> Data Set can be found here: